import type { Metadata } from "next";
// Use local / CSS-based font stack to avoid remote font downloads at build/runtime
import "./globals.css";

import { AuthProvider } from '@/lib/auth_context';
// We're not using next/font/google here to avoid Next.js trying to fetch
// fonts from Google (fonts.gstatic.com). The project already defines
// font-family CSS variables in `globals.css` and provides utility classes
// `.font-jakarta` and `.font-unbounded` — we'll use those instead.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`font-jakarta font-unbounded antialiased primary`}>
         <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
