import type { Metadata } from "next";
import { Plus_Jakarta_Sans, Unbounded } from "next/font/google";
import "./globals.css";

import { AuthProvider } from '@/lib/auth_context';
// Plus Jakarta Sans
const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-jakarta-sans",
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700","800"], 
  style: ["normal", "italic"],
});

// Poppins (optional)
const unbounded = Unbounded({
  variable: "--font-unbounded",
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700","800"],
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${jakartaSans.variable} ${unbounded.variable} antialiased primary`}>
         <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
